# Generated by Django 5.0.1 on 2024-01-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
