# Generated by Django 5.0.1 on 2024-01-15 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfeatures",
            name="other_images",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="product/"
            ),
            preserve_default=False,
        ),
    ]
