# Generated by Django 5.0.1 on 2024-01-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_productfeatures_other_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Updates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="updates/")),
                ("description", models.TextField()),
            ],
        ),
    ]
