# Generated by Django 5.0.1 on 2024-01-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_updates_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updates",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
