# Generated by Django 4.2.5 on 2024-01-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productfeatures",
            name="other_images",
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("other_images", models.ImageField(upload_to="product/")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.product",
                    ),
                ),
            ],
        ),
    ]
