# Generated by Django 4.2.5 on 2024-01-16 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_remove_productfeatures_other_images_productimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="name",
        ),
        migrations.AddField(
            model_name="updates",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
