# Generated by Django 4.2.5 on 2024-01-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(upload_to="gallery/")),
            ],
        ),
    ]
